# Generated by Django 4.2 on 2023-04-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('advmessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdviceMessages',
            new_name='AdviserMessages',
        ),
    ]
